# Generated by Django 4.1.8 on 2023-04-30 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mini_apps", "0001_initial"),
        ("base_messages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Name of Group")),
                ("created_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField()),
                ("deleted", models.BooleanField(default=False)),
                ("admins", models.ManyToManyField(related_name="admin_groups", to=settings.AUTH_USER_MODEL)),
                (
                    "messages",
                    models.ManyToManyField(related_name="base_message_groups", to="base_messages.basemessages"),
                ),
                ("mini_apps", models.ManyToManyField(related_name="mini_apps_groups", to="mini_apps.miniapps")),
                ("subscribers", models.ManyToManyField(related_name="subscriber_groups", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
