# Generated by Django 4.1.8 on 2023-04-30 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basemessages",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="base_messages", to="groups.group"
            ),
        ),
        migrations.AddField(
            model_name="basemessages",
            name="sender",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
