# Generated by Django 4.1.8 on 2023-04-30 12:34

from django.conf import settings
from django.db import migrations, models
import groups.mini_apps.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniApps",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Name of App")),
                ("modified_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                (
                    "app_type",
                    models.CharField(
                        choices=[
                            (groups.mini_apps.models.MiniAppType["TYPE_A"], "Order"),
                            (groups.mini_apps.models.MiniAppType["TYPE_B"], "Queue"),
                        ],
                        max_length=50,
                    ),
                ),
                ("config", models.JSONField()),
                ("deleted", models.BooleanField(default=False)),
                ("admins2", models.ManyToManyField(related_name="admin_mini_apps", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
