# Generated by Django 4.1.8 on 2023-04-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_apps", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="miniapps",
            old_name="admins2",
            new_name="admins",
        ),
        migrations.AlterField(
            model_name="miniapps",
            name="app_type",
            field=models.CharField(choices=[("TYPE_A", "Order"), ("TYPE_B", "Queue")], max_length=50),
        ),
    ]
